---
application:
  name: "crypto-backend"
  project: "Crypto"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "Crypto-database"
  version: "10"
routers:
- name: "main-crypto-backend"
  routes:
  - application_name: "crypto-backend"
    paths:
    - "/*"
